import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { useLocation, useParams } from 'react-router-dom';
import InputChatContent from '../components/InputChatContent';
import useChat from '../hooks/useChat';
import useChatApi from '../hooks/useChatApi';
import useChatList from '../hooks/useChatList';
import ChatMessage from '../components/ChatMessage';
import Button from '../components/Button';
import ButtonCopy from '../components/ButtonCopy';
import ModalDialog from '../components/ModalDialog';
import Select from '../components/Select';
import ScrollTopBottom from '../components/ScrollTopBottom';
import useFollow from '../hooks/useFollow';
import { PiShareFat } from 'react-icons/pi';
import { create } from 'zustand';
import useBranding from '../hooks/useBranding';
import { ChatPageQueryParams } from '../@types/navigate';
import { MODELS } from '../hooks/useModel';
import { getPrompter } from '../prompts';
import queryString from 'query-string';
import useFiles from '../hooks/useFiles';
import useDocumentGrounding from '../hooks/useDocumentGrounding';
import {
  GroundingSource,
  appendSourceFootnotes,
  buildGroundedSystemContext,
  stripSourceFootnotes,
} from '../utils/grounding';
import {
  AdditionalModelRequestFields,
  FileLimit,
} from 'generative-ai-use-cases';
import ModelParameters from '../components/ModelParameters';
import DocumentPreviewPanel from '../components/DocumentPreviewPanel';
import useDocumentPreview from '../hooks/useDocumentPreview';
import {
  IDLE_TURN_STATUS,
  TurnEvent,
  TurnStatus,
  nextTurnStatus,
} from '../utils/turnStatus';
import { AcceptedDotExtensions } from '../utils/MediaUtils';
import { useTranslation } from 'react-i18next';

// File size limits for Chat (Lambda route: API Gateway → Lambda → Bedrock Converse API)
// - Lambda synchronous payload limit: 6MB
// - File data is base64-encoded in the request, so max original file size ≈ 6MB / 1.33 ≈ 4.5MB
// - Bedrock Converse API document limit: 4.5MB per document (except Claude 4+ PDF and Nova PDF/DOCX)
const fileLimit: FileLimit = {
  accept: AcceptedDotExtensions,
  maxFileCount: 5,
  maxFileSizeMB: 4.5,
  maxImageFileCount: 20,
  maxImageFileSizeMB: 3.75,
  maxVideoFileCount: 1,
  maxVideoFileSizeMB: 1000, // 1 GB for S3 input
};

type StateType = {
  content: string;
  setContent: (c: string) => void;
};

const useChatPageState = create<StateType>((set) => {
  return {
    content: '',
    setContent: (s: string) => {
      set(() => ({
        content: s,
      }));
    },
  };
});

const DEFAULT_REASONING_BUDGET = 4096; // Claude 3.7 Sonnet recommended minimum value

const ChatPage: React.FC = () => {
  const { content, setContent } = useChatPageState();
  const { pathname, search, state } = useLocation();
  const {
    clear: clearFiles,
    uploadedFiles,
    uploadFiles,
    base64Cache,
  } = useFiles(pathname);
  const { chatId } = useParams();
  const { t } = useTranslation();
  const { logoPath } = useBranding();

  const {
    getModelId,
    setModelId,
    loading,
    writing,
    loadingMessages,
    isEmpty,
    messages,
    clear,
    postChat,
    editChat,
    setLoading,
    pushMessage,
    popMessage,
    updateSystemContext,
    updateSystemContextByModel,
    retryGeneration,
    forceToStop,
  } = useChat(pathname, chatId);
  const { createShareId, findShareId, deleteShareId } = useChatApi();
  const { documentGroundingEnabled, retrieveSources } = useDocumentGrounding();
  const { scrollableContainer, setFollowing } = useFollow();
  const { getChatTitle } = useChatList();
  const { modelDisplayName } = MODELS;
  const { data: share, mutate: reloadShare } = findShareId(chatId);
  const modelId = getModelId();
  const prompter = useMemo(() => {
    return getPrompter(modelId);
  }, [modelId]);
  const [overrideModelParameters, setOverrideModelParameters] =
    useState<AdditionalModelRequestFields>({
      reasoningConfig: {
        type: 'disabled',
        budgetTokens: DEFAULT_REASONING_BUDGET,
      },
    });
  const [showSetting, setShowSetting] = useState(false);

  // Retrieval runs against the knowledge base and the answer is generated by
  // the normal converse path, so every configured model stays available
  const availableModels = useMemo(() => {
    return MODELS.allModelIds;
  }, []);

  useEffect(() => {
    // On the conversation history page, do not change the system prompt even if the model is changed
    if (!chatId) {
      updateSystemContextByModel();
    }
    // eslint-disable-next-line  react-hooks/exhaustive-deps
  }, [prompter]);

  const title = useMemo(() => {
    if (chatId) {
      return getChatTitle(chatId) || t('chat.title');
    } else {
      return t('chat.new_chat');
    }
  }, [chatId, getChatTitle, t]);

  const accept = useMemo(() => {
    if (!modelId) return [];
    const feature = MODELS.getModelMetadata(modelId);
    return [
      ...(feature.flags.doc ? fileLimit.accept.doc : []),
      ...(feature.flags.image ? fileLimit.accept.image : []),
      ...(feature.flags.video ? fileLimit.accept.video : []),
    ];
  }, [modelId]);
  const fileUpload = useMemo(() => {
    return accept.length > 0;
  }, [accept]);
  const reasoning = useMemo(() => {
    return MODELS.getModelMetadata(modelId).flags.reasoning ?? false;
  }, [modelId]);
  const adaptiveThinking = useMemo(() => {
    return MODELS.getModelMetadata(modelId).flags.adaptiveThinking ?? false;
  }, [modelId]);
  const adaptiveThinkingAlwaysOn = useMemo(() => {
    return (
      MODELS.getModelMetadata(modelId).flags.adaptiveThinkingAlwaysOn ?? false
    );
  }, [modelId]);
  const xhighEffort = useMemo(() => {
    return MODELS.getModelMetadata(modelId).flags.xhighEffort ?? false;
  }, [modelId]);
  const reasoningEnabled = useMemo(() => {
    return (
      overrideModelParameters.reasoningConfig.type === 'enabled' ||
      overrideModelParameters.reasoningConfig.type === 'adaptive'
    );
  }, [overrideModelParameters]);
  // The effort / budget dialog only makes sense once thinking is on
  const setting = useMemo(() => {
    return reasoning && reasoningEnabled;
  }, [reasoning, reasoningEnabled]);

  // Whether reasoning was force-enabled by an always-on model while the
  // user had it disabled, so the disabled state can be restored later
  const reasoningForcedByAlwaysOn = useRef(false);

  // The sources that grounded the current turn, so a retry can re-render the
  // same citations without a second round trip
  const groundingSources = useRef<GroundingSource[]>([]);

  // When model changes, update reasoning type if reasoning is already enabled.
  // For models whose adaptive thinking is always on (e.g. Claude Sonnet 5),
  // reasoning is force-enabled while the model is selected, and the user's
  // original disabled state is restored when switching away.
  useEffect(() => {
    setOverrideModelParameters((prev) => {
      const config = prev.reasoningConfig;
      const enabled = config.type === 'enabled' || config.type === 'adaptive';

      let newType = config.type;
      if (adaptiveThinkingAlwaysOn) {
        if (!enabled) {
          reasoningForcedByAlwaysOn.current = true;
        }
        newType = 'adaptive';
      } else if (reasoningForcedByAlwaysOn.current) {
        reasoningForcedByAlwaysOn.current = false;
        newType = 'disabled';
      } else if (enabled) {
        newType = adaptiveThinking ? 'adaptive' : 'enabled';
      }

      const newEffort =
        config.effort === 'xhigh' && !xhighEffort ? 'high' : config.effort;
      if (config.type === newType && config.effort === newEffort) {
        return prev;
      }
      return {
        ...prev,
        reasoningConfig: { ...config, type: newType, effort: newEffort },
      };
    });
  }, [adaptiveThinking, adaptiveThinkingAlwaysOn, xhighEffort]);

  useEffect(() => {
    const _modelId = !modelId ? availableModels[0] : modelId;

    if (search !== '') {
      const params = queryString.parse(search) as ChatPageQueryParams;
      setContent(params.content ?? '');
      setModelId(
        availableModels.includes(params.modelId ?? '')
          ? params.modelId!
          : _modelId
      );
    } else {
      setModelId(_modelId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search, setContent, availableModels, pathname]);

  // "New chat" in the sidebar lands here with a marker in the history state
  useEffect(() => {
    if ((state as { newChat?: number } | null)?.newChat) {
      clear();
      setContent('');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);

  const lastQuestion = useMemo(() => {
    return [...messages].reverse().find((m) => m.role === 'user')?.content;
  }, [messages]);

  // What the in-flight turn is actually doing, driven by real events only
  const [turnStatus, setTurnStatus] = useState<TurnStatus>(IDLE_TURN_STATUS);
  const onTurnEvent = useCallback((event: TurnEvent) => {
    setTurnStatus((previous) => nextTurnStatus(previous, event));
  }, []);

  // Reasoning and answer deltas both land on the last assistant message -
  // Bedrock streams reasoningContent into `trace` - so the stream itself is the
  // event source, no extra plumbing through useChat
  useEffect(() => {
    if (!loading) {
      onTurnEvent({ type: 'turn-end' });
      return;
    }

    const last = messages[messages.length - 1];

    if (last?.role !== 'assistant') {
      return;
    }

    if ((last.content ?? '').trim() !== '') {
      onTurnEvent({ type: 'answer' });
    } else if ((last.trace ?? '') !== '') {
      onTurnEvent({ type: 'reasoning' });
    }
  }, [loading, messages, onTurnEvent]);

  const previewOpen = useDocumentPreview((state) => state.doc !== null);

  // Retrieve first, inject the passages into the system context, then let the
  // normal streaming chat answer. Attachments, history and reasoning are
  // untouched by this - the documents are just context.
  const groundTurn = useCallback(
    async (
      question: string,
      previousQuestion: string | undefined,
      showPlaceholder: boolean
    ): Promise<GroundingSource[]> => {
      if (!documentGroundingEnabled) {
        return [];
      }

      let sources: GroundingSource[] = [];

      setLoading(true);
      onTurnEvent({ type: 'retrieve-start' });

      if (showPlaceholder) {
        // Echo the question immediately so retrieval never looks like a freeze
        pushMessage('user', question);
        pushMessage('assistant', '');
      }

      try {
        sources = await retrieveSources(question, previousQuestion);
      } finally {
        onTurnEvent({ type: 'retrieve-settled', count: sources.length });

        if (showPlaceholder) {
          popMessage();
          popMessage();
        }
      }

      updateSystemContext(
        buildGroundedSystemContext(prompter.systemContext(pathname), sources)
      );
      groundingSources.current = sources;

      return sources;
    },
    [
      documentGroundingEnabled,
      prompter,
      pathname,
      retrieveSources,
      setLoading,
      pushMessage,
      popMessage,
      updateSystemContext,
      onTurnEvent,
    ]
  );

  const onSend = useCallback(async () => {
    setFollowing(true);
    onTurnEvent({ type: 'turn-start' });
    const savedContent = content;
    const previousQuestion = lastQuestion;
    setContent('');
    clearFiles();
    const sources = await groundTurn(savedContent, previousQuestion, true);
    const success = await postChat(
      prompter.chatPrompt({ content: savedContent }),
      false,
      stripSourceFootnotes,
      (message: string) => appendSourceFootnotes(message, sources),
      undefined,
      fileUpload ? uploadedFiles : undefined,
      undefined,
      undefined,
      undefined,
      base64Cache,
      overrideModelParameters
    );
    if (!success) {
      setContent(savedContent);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    content,
    base64Cache,
    fileUpload,
    groundTurn,
    lastQuestion,
    setFollowing,
    overrideModelParameters,
    uploadedFiles,
  ]);

  const onRetry = useCallback(async () => {
    onTurnEvent({ type: 'turn-start' });
    // The question has not changed, but re-grounding keeps citations correct
    // even after the conversation was restored from history
    const sources = lastQuestion
      ? await groundTurn(lastQuestion, undefined, false)
      : groundingSources.current;
    retryGeneration(
      false,
      stripSourceFootnotes,
      (message: string) => appendSourceFootnotes(message, sources),
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      base64Cache,
      overrideModelParameters
    );
  }, [
    retryGeneration,
    base64Cache,
    groundTurn,
    lastQuestion,
    overrideModelParameters,
    onTurnEvent,
  ]);

  const onStop = useCallback(() => {
    forceToStop();
  }, [forceToStop]);

  const onEdit = useCallback(
    async (modifiedPrompt: string) => {
      setFollowing(true);
      onTurnEvent({ type: 'turn-start' });
      const sources = await groundTurn(modifiedPrompt, undefined, false);
      editChat(
        modifiedPrompt,
        false,
        stripSourceFootnotes,
        (message: string) => appendSourceFootnotes(message, sources),
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        base64Cache,
        overrideModelParameters
      );
    },
    [
      editChat,
      base64Cache,
      groundTurn,
      setFollowing,
      overrideModelParameters,
      onTurnEvent,
    ]
  );

  const [creatingShareId, setCreatingShareId] = useState(false);
  const [deletingShareId, setDeletingShareId] = useState(false);
  const [showShareIdModal, setShowShareIdModal] = useState(false);
  const [isOver, setIsOver] = useState(false);

  const onCreateShareId = useCallback(async () => {
    try {
      setCreatingShareId(true);
      await createShareId(chatId!);
      reloadShare();
    } catch (e) {
      console.error(e);
    } finally {
      setCreatingShareId(false);
    }
  }, [chatId, createShareId, reloadShare]);

  const onDeleteShareId = useCallback(async () => {
    try {
      setDeletingShareId(true);
      await deleteShareId(share!.shareId.split('#')[1]);
      reloadShare();
    } catch (e) {
      console.error(e);
    } finally {
      setDeletingShareId(false);
    }
  }, [share, deleteShareId, reloadShare]);

  const shareLink = useMemo(() => {
    if (share) {
      return `${window.location.origin}/share/${share.shareId.split('#')[1]}`;
    } else {
      return null;
    }
  }, [share]);

  const handleDragOver = (event: React.DragEvent) => {
    // When a file is dragged, display the overlay
    event.preventDefault();
    setIsOver(true);
  };

  const handleDragLeave = (event: React.DragEvent) => {
    // When a file is dragged, hide the overlay
    event.preventDefault();
    setIsOver(false);
  };

  const handleDrop = (event: React.DragEvent) => {
    // When a file is dropped, add the file
    event.preventDefault();
    setIsOver(false);
    if (event.dataTransfer.files) {
      // Reflect the file and upload it
      uploadFiles(Array.from(event.dataTransfer.files), fileLimit, accept);
    }
  };

  return (
    <>
      <div
        onDragOver={fileUpload ? handleDragOver : undefined}
        className={`relative pb-44 transition-[padding] duration-200 ease-out ${
          previewOpen ? 'lg:pr-[max(420px,44vw)]' : ''
        }`}>
        <div className="invisible sticky top-0 z-10 h-0 border-[#EFEFEF] bg-white/90 backdrop-blur lg:visible lg:flex lg:h-14 lg:items-center lg:justify-between lg:border-b lg:px-6 print:hidden">
          <div className="truncate text-sm font-medium">{title}</div>
          {chatId && (
            <button
              className="focus-visible:ring-aws-squid-ink ml-4 flex flex-none items-center gap-1.5 rounded-lg px-2 py-1 text-[13px] text-[#5A5A5A] hover:bg-[#F7F7F7] focus:outline-none focus-visible:ring-1"
              onClick={() => {
                setShowShareIdModal(true);
              }}>
              <PiShareFat />
              {share ? <>{t('chat.sharing')}</> : <>{t('chat.share')}</>}
            </button>
          )}
        </div>

        {isOver && fileUpload && (
          <div
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
            className="fixed bottom-0 left-0 right-0 top-0 z-[999] bg-white/85 p-8 text-center backdrop-blur-sm">
            <div className="border-aws-squid-ink/40 text-aws-squid-ink flex h-full w-full items-center justify-center rounded-2xl border border-dashed">
              <div className="text-[15px] font-medium">
                {t('chat.drop_files')}
              </div>
            </div>
          </div>
        )}

        {(isEmpty || loadingMessages) && (
          <div className="flex h-[calc(100vh-20rem)] flex-col items-center justify-center gap-y-4 px-4 text-center">
            {logoPath ? (
              <img
                src={logoPath}
                alt=""
                className={`size-12 rounded-xl ${loadingMessages ? 'animate-pulse' : ''}`}
              />
            ) : null}
            {!loadingMessages && (
              <>
                <div className="text-aws-font-color text-2xl font-medium">
                  {t('chat.empty_greeting')}
                </div>
                <div className="max-w-md text-[13px] leading-relaxed text-[#969696]">
                  {t('chat.empty_hint')}
                </div>
              </>
            )}
          </div>
        )}

        <div ref={scrollableContainer} className="pt-4">
          {!isEmpty &&
            !loadingMessages &&
            messages.map((chat, idx) => (
              <ChatMessage
                key={idx}
                idx={idx}
                chatContent={chat}
                loading={loading && idx === messages.length - 1}
                allowRetry={idx === messages.length - 1}
                editable={idx === messages.length - 2 && !loading}
                onCommitEdit={
                  idx === messages.length - 2 && !loading ? onEdit : undefined
                }
                retryGeneration={onRetry}
                turnStatus={
                  idx === messages.length - 1 ? turnStatus : undefined
                }
              />
            ))}
        </div>

        <div
          className={`fixed right-4 top-[calc(50vh-2rem)] z-0 lg:right-8 ${
            previewOpen ? 'lg:hidden' : ''
          }`}>
          <ScrollTopBottom />
        </div>

        <div
          className={`fixed bottom-0 left-0 right-0 z-0 flex flex-col items-center justify-center bg-gradient-to-t from-white via-white to-transparent pt-8 transition-[right] duration-200 ease-out lg:left-72 print:hidden ${
            previewOpen ? 'lg:right-[max(420px,44vw)]' : ''
          }`}>
          <InputChatContent
            content={content}
            disabled={loading && !writing}
            onChangeContent={setContent}
            onSend={() => {
              if (!loading) {
                onSend();
              } else {
                onStop();
              }
            }}
            hideReset={true}
            fileUpload={fileUpload}
            fileLimit={fileLimit}
            accept={accept}
            reasoning={reasoning && !adaptiveThinkingAlwaysOn}
            onReasoningSwitched={() => {
              setOverrideModelParameters({
                ...overrideModelParameters,
                reasoningConfig: {
                  ...overrideModelParameters.reasoningConfig,
                  type: reasoningEnabled
                    ? 'disabled'
                    : adaptiveThinking
                      ? 'adaptive'
                      : 'enabled',
                },
              });
            }}
            reasoningEnabled={reasoningEnabled}
            setting={setting}
            onSetting={() => {
              setShowSetting(true);
            }}
            canStop={writing}
            toolbar={
              <div className="relative min-w-0">
                <Select
                  quiet
                  notItem
                  value={modelId}
                  onChange={setModelId}
                  options={availableModels.map((m) => {
                    return { value: m, label: modelDisplayName(m) };
                  })}
                />
              </div>
            }
          />
        </div>
      </div>

      {/* One panel for the whole page: a second citation swaps its contents */}
      <DocumentPreviewPanel />

      <ModalDialog
        isOpen={showShareIdModal}
        title={t('chat.share_conversation')}
        onClose={() => {
          setShowShareIdModal(false);
        }}>
        <div className="py-3 text-[13px] text-[#5A5A5A]">
          {share ? (
            <>{t('chat.delete_link_message')}</>
          ) : (
            <>{t('chat.create_link_message')}</>
          )}
        </div>
        {shareLink && (
          <div className="my-2 flex flex-row items-center justify-between rounded-lg border border-[#E8E8E8] bg-[#F7F7F7] px-3 py-2">
            <div className="break-all text-[13px]">{shareLink}</div>
            <ButtonCopy text={shareLink} />
          </div>
        )}
        <div className="flex justify-end py-3">
          {share ? (
            <div className="flex">
              <Button
                onClick={() => {
                  window.open(shareLink!, '_blank', 'noreferrer');
                }}
                outlined
                className="mr-1"
                loading={deletingShareId}>
                {t('chat.open_link')}
              </Button>
              <Button
                onClick={onDeleteShareId}
                loading={deletingShareId}
                className="border-red-500 bg-red-500">
                {t('chat.delete_link')}
              </Button>
            </div>
          ) : (
            <Button onClick={onCreateShareId} loading={creatingShareId}>
              {t('chat.create_link')}
            </Button>
          )}
        </div>
      </ModalDialog>
      <ModalDialog
        isOpen={showSetting}
        onClose={() => {
          setShowSetting(false);
        }}
        title={t('chat.advanced_options')}>
        {setting && (
          <ModelParameters
            modelFeatureFlags={MODELS.getModelMetadata(modelId).flags}
            overrideModelParameters={overrideModelParameters}
            setOverrideModelParameters={setOverrideModelParameters}
          />
        )}
        <div className="mt-4 flex justify-end">
          <Button
            onClick={() => {
              setShowSetting(false);
            }}>
            {t('chat.settings')}
          </Button>
        </div>
      </ModalDialog>
    </>
  );
};

export default ChatPage;
